# 指定kafka server的地址，集群配多个，中间，逗号隔开
spring:
  kafka:
    bootstrap-servers: 192.168.0.18:32400,192.168.0.18:32401,192.168.0.18:32402
  # 生产组配置
  producer:
    #重试次数
    retries: 3
    #批量发送的消息数量
    batch-size: 1000
    #32MB的批处理缓冲区
    buffer-memory: 33554432
    #消费者组配置
    consumer:
      group-id: crm-user-service
      #最早未被消费的offset
      auto-offset-reset: earliest
      #批量一次最大拉取数据量
      max-poll-records: 4000
      #是否自动提交
      enable-auto-commit: true
      #自动提交时间间隔，单位ms
      auto-commit-interval: 1000
