server:
  port: 8081

spring:
  application:
    name: springboot-log-log4j2-demo
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

logging:
  config: classpath:log4j2.xml
