### 保存用户信息
POST http://localhost:8082/demo/user/save
Content-Type: application/json

{
  "name": "yunnuo",
  "age": 23,
  "sex": 1,
  "email": "2552846359@qq.com"
}


### 分页查询(mybatis-plus)用户信息列表
POST http://localhost:8082/demo/user/pageForMp
Content-Type: application/json

{
  "name": "Tom",
  "current":1,
  "size": 2
}


### 分页查询(pagehelper)用户信息列表
POST http://localhost:8082/demo/user/pageForPageHelper
Content-Type: application/json

{
  "name": "Tom",
  "current":1,
  "size": 2
}


### 根据id获取用户信息
GET http://localhost:8082/demo/user/getById/1

### 响应示例
# {
#  "code": 200,
#  "msg": "操作成功",
#  "res": {
#    "id": 1,
#    "name": "yunnuo",
#    "age": 23,
#    "sex": 1,
#    "email": "2552846359@qq.com"
#  }
# }

### User Map结构返回测试
POST http://localhost:8082/demo/user/mapDemo
Content-Type: application/json

[1]
