knife4j:
  enable: true
  openapi:
    title: Knife4j接口文档
    description: "这是个介绍文档"
    email: 2552846359@qq.com
    concat: 云诺
    url: https://gitee.com/linyunnuo/springboot-demo
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      test1:
        group-name: spring-boot-knife4j-demo
        api-rule: package
        api-rule-resources:
          - com.ukayunnuo.controller
