server:
  port: 8090

spring:
  application:
    name: springboot-jwt-demo
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  profiles:
    active:
      - security-jwt
