spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master: # 默认数据源
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
          url: jdbc:p6spy:mysql://${KBK_MASTER_IP:127.0.0.1}:${KBK_MASTER_PORT:3306}/KBK?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&characterEncoding=utf8
          username: ${KBK_MASTER_USER:root}
          password: ${KBK_MASTER_PASSWD:root}
        slave:
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
          url: jdbc:p6spy:mysql://${KBK_SLAVE_IP:127.0.0.1}:${KBK_SLAVE_PORT:3306}/KBK_SLAVE?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&characterEncoding=utf8
          username: ${KBK_SLAVE_USER:root}
          password: ${KBK_SLAVE_PASSWD:root}
        other:
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
          url: jdbc:p6spy:mysql://${KBK_OTHER_IP:127.0.0.1}:${KBK_OTHER_PORT:3306}/KBK_OTHER?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&characterEncoding=utf8
          username: ${KBK_OTHER_USER:root}
          password: ${KBK_OTHER_PASSWD:root}
      druid:
        initial-size: 1
        min-idle: 1
        max-active: 10
        max-wait: 60000
        async-init: true
        query-timeout: 30000
#    type: com.zaxxer.hikari.HikariDataSource # 需要pom依赖HikariCP
#    hikari:
#      pool-name: DateHikariCP
#      minimum-idle: 5
#      idle-timeout: 180000
#      maximum-pool-size: 10
#      auto-commit: true
#      max-lifetime: 1800000
#      connection-timeout: 30000
#      connection-test-query: SELECT 1

# mybatis-plus 配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:**/*Mapper.xml
  global-config:
    db-config:
      # 1 代表已删除，不配置默认是1，也可修改配置
      logic-delete-value: 1
      # 0 代表未删除，不配置默认是0，也可修改配置
      logic-not-delete-value: 0
      # 添加非空判断
      field-strategy: not_empty
      # 是否开启表名自动驼峰命名规则
      table-underline: true
  # 日志配置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN（下划线命名） 到经典 Java 属性名 aColumn（驼峰命名） 的类似映射
    map-underscore-to-camel-case: true
    # 开启二级缓存
    cache-enabled: true
