server:
  port: 8080

spring:
  application:
    name: springboot-webclient-demo
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  profiles:
    active:
      - webclient