### 测试token 白名单
POST http://localhost:8090/security/jwt/demo/whiteTokenTest

### 登录获取token测试
POST http://localhost:8090/security/jwt/demo/login
Content-Type: application/json

{
  "uid": 1,
  "userName": "yunnuo"
}

### 根据token获取用户信息
POST http://localhost:8090/security/jwt/demo/getUserInfo
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxIiwic3ViIjoieXVubnVvIiwiaWF0IjoxNzA0NDUxNDkxLCJ1aWQiOjEsInVzZXJOYW1lIjoieXVubnVvIiwiZXhwIjoxNzA0NDUzMjkxfQ.ECF1-UhNq4mmIxZacNfoNTJHWwb4SpAIqYnCxVnYcoQ

{
  "uid": 1,
  "userName": "yunnuo"
}
