spring:
  #redis配置 集群版本
  redis:
    cluster:
      # 集群地址
      nodes: 127.0.0.1:6380,127.0.0.1:6381,127.0.0.1:6382,127.0.0.1:6383
    # 密码
    password: ${SPRINGBOOT_DEMO_REDIS_PWD:}
    # 数据库
    database: ${SPRINGBOOT_DEMO_REDIS_DATABASE:0}
    # 连接超时时间
    timeout: 1000
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 20
        max-wait: -1ms
    jedis:
      pool:
        max-active: 200
        max-wait: -1ms
        max-idle: 10
        min-idle: 2